### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by MoeexT** [arbellea/DeepCellSeg#1]
Tried to run main.py, but a little problem happened:
'''
Traceback (most recent call last):
  File "main.py", line 771, in <module>
    trainer.build(batch_size=10)
  File "main.py", line 539, in build
    train_image_batch, train_seg_batch = self.train_csv_reader.get_batch(batch_size)
ValueError: too many values to unpack (expected 2)
'''
Tried to analysis the code but given the limited level，I don‘t know how to deal with it.

**Comment by arbellea** [comment]
Thanks, 
looking into it

**Comment by arbellea** [comment]
I cleaned the code and fixed all the issues I found. 
You can now run the code from SourceCode/AdverserialSeg/main_GAN.py
Please make sure to convert the data to the desired format. If you are using ISBI Cell tracking data data you can use the MATLAB script in MATLAB-scripts/convert_isbi_to_net.m
