### ISSUE TITLE
Is the output of the estimator the same as the input image?

### ISSUE THREAD

**Issue by hsm207** [arbellea/DeepCellSeg#6]
Section 2.4.1 of the paper says:

> The output of the estimator is an image with the same size as the input image with three channels corresponding to the probability that a pixel belongs to the background, foreground or cell contour.

But in the code, `SegNetG` does the convolutions with `padding='valid'`. But this means that the output of this `SegNetG` will not be the same as the input image.

Is there a post processing step somewhere to resize the output of `SegNetG` or am I missing something?

**Comment by arbellea** [comment]
You are right, the padding of the generator should be 'SAME"
I'll change it soon
